services:
  reactjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
    volumes:
      - ./src:/usr/src/app/src





