services:
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
  postgresql_db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_docker
      POSTGRES_USER: postgres




