services:
  nestjs-api-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '5001:5001'
    environment:
      - PORT=5001
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src

